# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/configuration/ and in linters documentation

ANSIBLE_ANSIBLE_LINT_PRE_COMMANDS:
  - command: |
      mkdir -pv "${HOME}/.ansible/roles" && \
      cd "${HOME}/.ansible/roles" && \
      ln -sv ../../../workspace "${GITHUB_REPOSITORY#*/}"

BASH_SHFMT_ARGUMENTS: --case-indent --indent 2 --space-redirects

DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - MARKDOWN_MARKDOWN_LINK_CHECK # Using lychee instead
  - SPELL_CSPELL
  - TERRAFORM_TERRASCAN # Hard to configure - no documentation of the config file
  - YAML_V8R

# Remove: To receive reports as email, please set variable EMAIL_REPORTER_EMAIL
EMAIL_REPORTER: false

FAIL_IF_MISSING_LINTER_IN_FLAVOR: true

FILTER_REGEX_EXCLUDE: CHANGELOG.md

FORMATTERS_DISABLE_ERRORS: false

MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yml
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: CHANGELOG.md

# Remove initial MegaLinter graphic
PRINT_ALPACA: false

# Disable creating report directory
REPORT_OUTPUT_FOLDER: none

REPOSITORY_CHECKOV_ARGUMENTS: --quiet

# Do not leave debug code in production, Insecure URL
REPOSITORY_DEVSKIM_ARGUMENTS: --ignore-globs CHANGELOG.md --ignore-rule-ids DS162092,DS137138

REPOSITORY_KICS_ARGUMENTS: --fail-on high

REPOSITORY_TRIVY_ARGUMENTS: --ignorefile .trivyignore.yaml --severity HIGH,CRITICAL --ignore-unfixed

TERRAFORM_TFLINT_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN

TYPESCRIPT_PRETTIER_ARGUMENTS: --html-whitespace-sensitivity=ignore

VALIDATE_ALL_CODEBASE: true

YAML_PRETTIER_ARGUMENTS: --no-error-on-unmatched-pattern
