---
# tasks file for proxy_settings

- name: Configure proxy settings for OS (/etc/environment)
  blockinfile:
    dest: /etc/environment
    create: yes
    mode: u=rw,g=r,o=r
    block: |
      {% if proxy_settings_http_proxy is defined %}
      http_proxy="{{ proxy_settings_http_proxy }}"
      HTTP_PROXY="{{ proxy_settings_http_proxy }}"
      {% endif %}
      {% if proxy_settings_ftp_proxy is defined %}
      ftp_proxy="{{ proxy_settings_ftp_proxy }}"
      FTP_PROXY="{{ proxy_settings_ftp_proxy }}"
      {% endif %}
      {% if proxy_settings_https_proxy is defined %}
      https_proxy="{{ proxy_settings_https_proxy }}"
      HTTPS_PROXY="{{ proxy_settings_https_proxy }}"
      {% endif %}
      {% if proxy_settings_no_proxy is defined %}
      no_proxy="{{ proxy_settings_no_proxy }}"
      NO_PROXY="{{ proxy_settings_no_proxy }}"
      {% endif %}
  tags: proxy

- name: Configure proxy settings for OS (/etc/profile.d/proxy.sh)
  template:
    src: proxy.sh.j2
    dest: /etc/profile.d/proxy.sh
    mode: u=rw,g=r,o=r
  tags: proxy

- name: Check if systemd/system.conf exists
  ansible.builtin.stat:
    path: /etc/systemd/system.conf
  register: systemd_system_conf
  tags: proxy

- name: Configure proxy settings for systemd services
  ansible.builtin.lineinfile:
    path: /etc/systemd/system.conf
    regexp: "^DefaultEnvironment="
    line: >-
      DefaultEnvironment={% if proxy_settings_ftp_proxy is defined %}"FTP_PROXY={{ proxy_settings_ftp_proxy }}"{% endif %}
      {% if proxy_settings_http_proxy is defined %}"HTTP_PROXY={{ proxy_settings_http_proxy }}"{% endif %}
      {% if proxy_settings_https_proxy is defined %}"HTTPS_PROXY={{ proxy_settings_https_proxy }}"{% endif %}
      {% if proxy_settings_no_proxy is defined %}"NO_PROXY={{ proxy_settings_no_proxy }}"{% endif %}
      {% if proxy_settings_ftp_proxy is defined %}"ftp_proxy={{ proxy_settings_ftp_proxy }}"{% endif %}
      {% if proxy_settings_http_proxy is defined %}"http_proxy={{ proxy_settings_http_proxy }}"{% endif %}
      {% if proxy_settings_https_proxy is defined %}"https_proxy={{ proxy_settings_https_proxy }}"{% endif %}
      {% if proxy_settings_no_proxy is defined %}"no_proxy={{ proxy_settings_no_proxy }}"{% endif %}
  when: systemd_system_conf.stat.exists
  notify: systemd daemon-reload
  tags: proxy

- name: Check if wgetrc exists
  stat:
    path: /etc/wgetrc
  register: wgetrc
  tags: proxy

- name: Add proxy settings to wgetrc (if exists)
  blockinfile:
    dest: /etc/wgetrc
    mode: u=rw,g=r,o=r
    block: |
      use_proxy = on
      {% if proxy_settings_http_proxy is defined %}
      http_proxy = {{ proxy_settings_http_proxy }}
      {% endif %}
      {% if proxy_settings_https_proxy is defined %}
      https_proxy = {{ proxy_settings_https_proxy }}
      {% endif %}
      {% if proxy_settings_ftp_proxy is defined %}
      ftp_proxy = {{ proxy_settings_ftp_proxy }}
      {% endif %}
      {% if proxy_settings_no_proxy is defined %}
      no_proxy = {{ proxy_settings_no_proxy }}
      {% endif %}
  when: wgetrc.stat.exists
  tags: proxy

- name: Configure proxy settings for dnf
  lineinfile:
    dest: /etc/dnf/dnf.conf
    regexp: "^proxy="
    line: "proxy={{ proxy_settings_yum_proxy }}"
    mode: u=rw,g=r,o=r
  tags: proxy
  when: ansible_pkg_mgr == 'dnf' and proxy_settings_yum_proxy is defined

- name: Configure proxy_username for dnf
  lineinfile:
    dest: /etc/dnf/dnf.conf
    regexp: "^proxy_username="
    line: "proxy_username={{ proxy_settings_yum_proxy_username }}"
    mode: u=rw,g=r,o=r
  tags: proxy
  when: ansible_pkg_mgr == 'dnf' and proxy_settings_yum_proxy_username is defined

- name: Configure proxy_password for dnf
  lineinfile:
    dest: /etc/dnf/dnf.conf
    regexp: "^proxy_password="
    line: "proxy_password={{ proxy_settings_yum_proxy_password }}"
    mode: u=rw,g=r,o=r
  tags: proxy
  when: ansible_pkg_mgr == 'dnf' and proxy_settings_yum_proxy_password is defined

- name: Configure proxy settings for yum
  lineinfile:
    dest: /etc/yum.conf
    regexp: "^proxy="
    line: "proxy={{ proxy_settings_yum_proxy }}"
    mode: u=rw,g=r,o=r
  tags: proxy
  when: ansible_pkg_mgr == 'yum' and proxy_settings_yum_proxy is defined

- name: Configure proxy_username for yum
  lineinfile:
    dest: /etc/yum.conf
    regexp: "^proxy_username="
    line: "proxy_username={{ proxy_settings_yum_proxy_username }}"
    mode: u=rw,g=r,o=r
  tags: proxy
  when: ansible_pkg_mgr == 'yum' and proxy_settings_yum_proxy_username is defined

- name: Configure proxy_password for yum
  lineinfile:
    dest: /etc/yum.conf
    regexp: "^proxy_password="
    line: "proxy_password={{ proxy_settings_yum_proxy_password }}"
    mode: u=rw,g=r,o=r
  tags: proxy
  when: ansible_pkg_mgr == 'yum' and proxy_settings_yum_proxy_password is defined

- name: Configure proxy settings for apt-get/aptitude
  template:
    src: 80proxy.j2
    dest: /etc/apt/apt.conf.d/80proxy
    mode: u=rw,g=r,o=r
  tags: proxy
  when: ansible_pkg_mgr == 'apt'

- name: Configure proxy settings for Suse
  template:
    src: proxy.j2
    dest: /etc/sysconfig/proxy
    mode: u=rw,g=r,o=r
  tags: proxy
  when: ansible_pkg_mgr == 'zypper'
