---
- name: Converge
  hosts: all

  vars:
    # kics-scan ignore-line
    proxy_settings_http_proxy: "http://myuser:********@px01.example.com:3128"
    proxy_settings_ftp_proxy: "http://proxy.example.com:8080"
    proxy_settings_https_proxy: "http://px01.example.com:3128"
    proxy_settings_no_proxy: "example.com,192.168.122.1"
    proxy_settings_yum_proxy: "http://proxysrv:8080"
    proxy_settings_yum_proxy_username: "myuser"
    # kics-scan ignore-line
    proxy_settings_yum_proxy_password: "********"

  roles:
    - role: ansible-role-proxy_settings
